const endUrl = {
    login: 'login',
    resetPassword: 'forget-password',
    logout: 'user/logout',
    schoolDistList: 'user/school-district',
    schoolList: 'user/school',
    searchSchool: 'user/search/school?query=',
    districtSearch: 'user/search/district?query=',
    organisation: 'user/organization',
    userList: 'user/manage',
    addUser: 'user/manage',
    usersearch: 'user/search/query?query=',
    allPermission: 'all-permissions',
    stockCategorySearch: 'user/search/stock-category?query=',
    stockCategoryList : 'user/stock-category',
    stockitemList:'user/stock-item',
    stockItemSearch:'user/search/stock-item?query=',
    collectionreqList:'user/furniture-collection-request', 
    categoryWiseItem : 'user/stock-category',
    addFurRequest :"user/furniture-collection-request",
    getManageRequest: "user/furniture-manage-collection/list",
    statusList:'user/status/get-all-status',
    searchfurRequest:'user/search/furniture-collection-request',
    delManageRequest: 'user/furniture-collection-request',
    searchManageRequest: 'user/search/furniture-collection-manage',
    acceptCollectionReuest:'user/furniture-collect',
    annexure: 'user/download/annexure/a',
    replanishStatus : 'user/status/get-all-replenishment-status',
    annexureB:'user/download/annexure/b',
    annexureC:'user/download/annexure/c',
    uploadProofReplanishment : 'user/file/upload/proof-of-replenishment',
    annexureD:'user/download/annexure/d',
    submitRepair :'user/furniture-collect/repair-submit',
    finalDelivery :'user/collection/deliver-collection',
    CMC_List :'user/school-cmc',
    CMC_search:'user/search/school-cmc?query=',
    CIRCUIT_List:'user/school-circuit',
    CIRCUIT_search:"user/search/school-circuit?query=",
    SubPlace_List:'user/school-subplace',
    SubPlaces_search:"user/search/school-subplace?query=",
    singleRequest :"user/furniture-collect",
    single_distrequest:"user/school-district",
    single_cmcrequest :'user/school-cmc',
    single_circuitrequest:'user/school-circuit',
    school_snq :'user/list/school-snq',
    school_level :'user/list/school-level',
    searchBy_ReferenceNumber : 'user/collection-request/search/reference-number',
    searchBy_DateRange : 'user/collection-request/search/date-range',
    
}
export default endUrl;