const endUrl = {
    login: 'login',
    resetPassword: 'forget-password',
    logout: 'user/logout',
    schoolDistList: 'user/school-district',
    schoolList: 'user/school',
    searchSchool: 'user/search/school?query=',
    districtSearch: 'user/search/district?query=',
    organisation: 'user/organization',
    userList: 'user/manage',
    addUser: 'user/manage',
    usersearch: 'user/search/query?query=',
    allPermission: 'all-permissions',
    stockCategorySearch: 'user/search/stock-category?query=',
    stockCategoryList : 'user/stock-category',
    stockitemList:'user/stock-item',
    stockItemSearch:'user/search/stock-item?query=',
    collectionreqList:'user/furniture-collection-request',
    categoryWiseItem : 'user/stock-category',
    addFurRequest :"user/furniture-collection-request",
    statusList:'user/status/get-all-status',
    searchfurRequest:'user/search/furniture-collection-request',
    delManageRequest: 'user/furniture-collection-request',
    searchManageRequest: 'user/search/furniture-collection-manage',
    acceptCollectionReuest:'user/furniture-collect/',

}
export default endUrl;