const Images = {
    CompanyLogo: require('./images/Logo1.png'),
    Eye: require('./images/eye.png'),
    Eye_off: require('./images/eye_off.png'),
    right: require('./images/emailSentTick.png'),
    error: require('./images/error.png'),
    Calender: require('./images/calender.png'),
    Calendar: require('./images/calendar.png'),
    DownArrow: require('./images/downarrow.png'),
    SearchIcon: require('./images/search.png'),
    deleteIcon: require('./images/delete.png'),
    editIcon: require('./images/edit.png'),
    leftarrow: require('./images/cricleleftarrow.png'),
    rightarrow: require('./images/criclerightarrow.png'),
    closeimage: require('./images/closeIcon.png'),
    addCricleIcon: require('./images/AddCircle.png'),
    rightIcon: require('./images/rightIcon.png'),
    DownArrow: require('./images/downarrow.png'),
    SearchIcon: require('./images/search.png'),
    deleteIcon: require('./images/delete.png'),
    editIcon: require('./images/edit.png'),
    leftarrow: require('./images/cricleleftarrow.png'),
    rightarrow: require('./images/criclerightarrow.png'),
    closeimage: require('./images/closeIcon.png'),
    addCricleIcon: require('./images/AddCircle.png'),
    headerLine: require('./images/headerLine.png'),
    transactionlist: require('./images/TransactionList.png'),
    createRequestSuccess: require('./images/createrequestsuccess.png'),
    collectFurnitureScccess: require('./images/collectFurscuccess.png'),
    repairReplanishSuccess: require('./images/repairsuccess.png'),
    rightArrowSuccess: require('./images/rightarrow.png'),
    dilveryIconInProgress: require('./images/dilveryinprogress.png'),
    SearchIconWhite: require('./images/searchIconWhite.png'),
    PrintIcon : require('./images/PrintIcon.png')
}
export default Images