/* LOGIN CONSTANT */
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCEESS = 'LOGIN_SUCEESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

/* PASSWORD RESET */
export const RESET_REQUEST = 'RESET_REQUEST'
export const RESET_SUCEESS = 'RESET_SUCEESS'
export const RESET_ERROR = 'RESET_ERROR'
