const AlertText = {
    SigoutMessage: 'Do you want to signout ?',
    UndoMessgae: 'You Cannot Undo This action',
    cancelProcessMessgae: 'Do you want to cancel the process ?',
    DeleteUser: 'Do You Want To Delete This User ?',
    deletedistrict: 'Do You Want To Delete This Distict',
    deleteschool: 'Do You Want To Delete This School',
    signout: 'Do you want to Signout ?',
    districtAdd: 'New district added successfully!',
    districtAddedSub: 'School District Added Successfully',
    districtUpdate: 'Updated Successfully',
    districtUpdateSub: 'School District Updated Successfully',
    SchoolUpdate: 'Updated Successfully',
    SchoolUpdateSub: 'School User Updated Successfully',
    AddedSuccessFully: 'Added Successfully',
    SchoolAddedSub: 'School Added Successfully',
    districtAdded: 'District is already added',
    schoolAdded: 'School is already added',
    editfailure: 'Please try To edit again',
    createSuccess: 'User Created Successful',
    updateSuccess: 'User Updated Successful',
    deleteUser: 'Do you want to delete this User?',
    canNotUndo: 'You cannot undo this action',
    deleteStockCategory: 'Do you want to delete this Category?',
    deleteStock :'Are you sure you want to delete?',
    submitMessage:'Do you Want to submit',
    deleteManageRequest: 'Are you sure you want to delete this request?',
    GoToTransactionList:'Information that is not saved will be lost, are you sure you want to leave the current page?',
    saveMsgIntransc :'The captured information has been saved successfully',
    
}
export default AlertText