const Dummydatauser = [
  {
    id: 1,
    Name: "Jonathan",
    Surnmae: "Amral",
    Username: "500100196",
    Emailid: "Jonathan.Amral@co.za",
    Organisation: "school",
  },
  {
    id: 2,
    Name: "Naman",
    Surnmae: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 3,
    Name: "Tanmay",
    Surnmae: "Singh",
    Username: "500100185",
    Emailid: "Tanmay.Singh@co.za",
    Organisation: "Dinovation",
  },
  {
    id: 4,
    Name: "Goldy",
    Surnmae: "Jain",
    Username: "500100189",
    Emailid: "Goldy.jain@co.za",
    Organisation: "School",
  },
  {
    id: 5,
    Name: "Animesh",
    Surnmae: "Agarwal",
    Username: "500100107",
    Emailid: "Animesh.Agawal@co.za",
    Organisation: "Dinovation",
  },
  {
    id: 6,
    Name: "Harmandeep",
    Surnmae: "Mavi",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 2,
    Name: "Naman",
    Surnmae: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 7,
    Name: "Naman",
    Surnmae: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 8,
    Name: "Naman",
    Surnmae: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
];
ß
export default Dummydatauser;
