const Dummydatauser = [
  {
    id: 1,
    Name: "Jonathan",
    Surname: "Amral",
    Username: "500100196",
    Emailid: "Jonathan.Amral@co.za",
    Organisation: "school",
  },
  {
    id: 2,
    Name: "Naman",
    Surname: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 3,
    Name: "Tanmay",
    Surname: "Singh",
    Username: "500100185",
    Emailid: "Tanmay.Singh@co.za",
    Organisation: "Dinovation",
  },
  {
    id: 4,
    Name: "Goldy",
    Surname: "Jain",
    Username: "500100189",
    Emailid: "Goldy.jain@co.za",
    Organisation: "School",
  },
  {
    id: 5,
    Name: "Animesh",
    Surname: "Agarwal",
    Username: "500100107",
    Emailid: "Animesh.Agawal@co.za",
    Organisation: "Dinovation",
  },
  {
    id: 6,
    Name: "Harmandeep",
    Surname: "Mavi",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 7,
    Name: "Naman",
    Surname: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 8,
    Name: "Naman",
    Surname: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
  {
    id: 9,
    Name: "Naman",
    Surname: "Mathur",
    Username: "500100187",
    Emailid: "Naman.mathur@co.za",
    Organisation: "School",
  },
];

export default Dummydatauser;
