const Dummydatafunctionalities = [
    {
      id: 1,
      Task: "Furniture Replacment - Collect Furniture item ",
      Create: true,
      Read: false,
      Update: false,
      delete: false,
    },
    {
      id: 2,
      Task: "Furniture Replacment - Create collection request ",
      Create: false,
      Read: true,
      Update: true,
      delete: false,
    },
    {
      id: 3,
      Task:"Furniture Replacment - Dilver furniture",
      Create: true,
      Read: true,
      Update: true,
      delete: false,
    },
    {
      id: 4,
      Task: "Furniture Replacment - Repair Replanish Funiture",
      Create: false,
      Read: true,
      Update: true,
      delete: true,
    },
    {
      id: 5,
      Task: "Manage Reuest",
      Create: false,
      Read: false,
      Update: false,
      delete: false,
    },
    {
      id: 6,
      Task: "Reports",
      Create: false,
      Read: true,
      Update: false,
      delete: false,
    },
    {
      id: 7,
      Task: "maintanence - Stock Categories",
      Create: false,
      Read: false,
      Update: true,
      delete: false,
    },
    {
      id: 8,
      Task: "maintanence -  Stock Item ",
      Create: true,
      Read: true,
      Update: true,
      delete: true,
    },
    {
      id: 9,
      Task: "maintanence - Load repair stock",
      Create: false,
      Read: false,
      Update: false,
      delete: false,
    },
    {
        id: 10,
        Task: "System Adimn - Manage user",
        Create: false,
      Read: true,
      Update: true,
      delete: false,
      },
  ];
  
  export default Dummydatafunctionalities;
  